name: Build and push Docker image

on:
  push:
    branches:
      - main
      - dev-*
  workflow_dispatch: {}

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Compute lowercase repo info
        id: repoinfo
        run: |
          echo "owner=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_OUTPUT
          repo=${GITHUB_REPOSITORY#*/}
          echo "repo=${repo,,}" >> $GITHUB_OUTPUT

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: ATC4-HQ-SERVER
          file: Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ steps.repoinfo.outputs.owner }}/${{ steps.repoinfo.outputs.repo }}:latest
            ghcr.io/${{ steps.repoinfo.outputs.owner }}/${{ steps.repoinfo.outputs.repo }}:${{ github.sha }}
